### ISSUE TITLE
Implement Basic Calculator Functions in C++

### ISSUE THREAD

**Issue by KALIIOWORK** [KALIIOWORK/basic_c-_programs#6]
Get hands-on with C++ by building a basic calculator! This beginner-level task will help you practice fundamental arithmetic operations and user input handling, essential skills for any aspiring programmer.

**Task:**
Your challenge is to create a C++ program that functions as a basic calculator. It should be able to perform addition, subtraction, multiplication, and division operations based on user input. The program should handle both integers and floating-point numbers.

**Instructions:**
1. Fork this repository to your GitHub account.
2. Clone the forked repository to your local machine: `git clone https://github.com/KALIIOWORK/basic_c-_programs.git`
3. Create a new C++ file named `calculator.cpp`.
4. Write a program that takes user input for two numbers and an operation (+, -, *, /).
5. Implement the corresponding operation and display the result.
6. Ensure your program handles both integers and floating-point numbers.
7. Test your calculator with various input scenarios to validate its functionality.
8. Compile and run your program to ensure it works correctly.
9. Commit your changes and push them to your forked repository.
10. Open a pull request with your changes.

**Note:**
This task will strengthen your understanding of user input processing and basic arithmetic operations in C++. Have fun building your calculator! Good luck! 🧮✨

**Comment by Tashuuuu** [comment]
Can I work on it?
